BitLyric/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.bitlyric.urls', namespace="bitlyric",
                      app_name='bitlyric')),

    url(r'^admin/', include(admin.site.urls)),
]

apps/bitlyric/urls.py
from django.conf.urls import url

from .views import Index, Lyric, Artist, Search

urlpatterns = [

    url(r'^$', Index.as_view(), name='index'),

    url(r'^artista/(?P<artist>[\w\-]+)/$', Artist.as_view(), name='artista'),

    url(r'^(?P<artista>[\w\-]+)/cancion/(?P<cancion>[\w\-]+)/$',
        Lyric.as_view(), name='cancion')
    ,
    url(r'^search$', Search.as_view(), name='search'),

]

"""
Esto solo funciona en ambiente de desarrollo para poder servir los
archivos que los usuario van subiendo a la web.
"""
from django.conf import settings

if settings.DEBUG == True:
     urlpatterns += (
         url(r'media/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT}
         ),
     )

apps/bitlyric/models.py
from django.db import models
from django.utils.text import slugify


class Artistas(models.Model):
    name = models.CharField(max_length=150)
    img = models.ImageField(upload_to='artistas', blank=True, null=True)
    slug = models.SlugField(editable=False)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        
        super(Artistas, self).save(*args, **kwargs)


class Musica(models.Model):
    title = models.CharField(max_length=350)
    link = models.CharField(max_length=350)
    letra = models.TextField()
    artistas = models.ManyToManyField(Artistas)
    slug = models.SlugField(editable=False)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)

        if self.link.startswith('http'):
            self.link = self.link[self.link.find('=')+1 :: ]

        super(Musica, self).save(*args, **kwargs)

apps/bitlyric/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from apps.bitlyric.models import Artistas, Musica


class Index(TemplateView):
    template_name = 'bitlyric/index.html'


class Artist(TemplateView):
    template_name = 'bitlyric/artist_page.html'

    def get_context_data(self, **kwargs):
        context = super(Artist, self).get_context_data(**kwargs)

        # agarra el valor que viene en la variable artista de la URL
        artista = Artistas.objects.get(slug=kwargs['artist'])

        # para poder acceder a las propiedades del artista en el template
        # debes usar la variable {{ artist }}, si lo deseas cambiarlo
        # debes de modificar en context['<nombre>'] donde <nombre> es lo
        # que usaras para mostrarlo en el template si lo camcbias
        # recuerda que tambien debes cambiarlos en los templates.
        context['artist'] = artista

        # filtra todas las canciones por el valor de la variable artista
        canciones = Musica.objects.filter(artistas=artista)

        # para poder acceder a las propiedades del artista en el template
        # debes usar la variable {{ canciones }}, si lo deseas puedes cambiarlo
        # recuerda que tambien debes cambiarlos en los templates.
        context['canciones'] = canciones

        return context


class Lyric(TemplateView):
    template_name = 'bitlyric/lyric_page.html'

    def get_context_data(self, **kwargs):
        context = super(Lyric, self).get_context_data(**kwargs)

        # agarra el valor que viene en la variable cancion de la URL
        cancion = Musica.objects.get(slug=kwargs['cancion'])
        context['cancion'] = cancion

        # agarra el valor que viene en la variable artista de la URL
        artista = Artistas.objects.get(slug=kwargs['artista'])
        context['artist'] = artista

        context['canciones'] = Musica.objects.filter(artistas=artista)

        return context


class Search(TemplateView):
    template_name = 'bitlyric/search.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        context['searched'] =  request.GET['music']

        canciones_relacionadas = Musica.objects.filter(title__contains=\
                                                       context['searched'])

        context["canciones"] = canciones_relacionadas


        return render(request, 'bitlyric/search.html', context )

templates/base.html
<!doctype html>
{% load staticfiles %}
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type='image/ico' href="{% static 'img/favicon.ico' %}"/>
    <title>{% block title %}
        bitLyric
    {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}" />
    <script src="{% static 'js/vendor/modernizr.js' %}"></script>
    {% block extra-css %}
    {% endblock %}


  </head>
  <body>
    

    <div class="row">
        <div class="large-3 columns">
            <a href="{% url 'bitlyric:index' %}">
                <h1>bitLyric</h1>
            </a>
        </div>
        <div class="large-9 columns right">
          <form method="get" action="{% url 'bitlyric:search' %}">
            <div class="row collapse">
              <div class="large-10 small-8 columns">
                <input name="music" type="text"/>
              </div>

              <div class="large-2 small-4 columns">
                  <input class="postfix button expand" type="submit" value="Search"/>
              </div>
            </div>
          </form>
        </div>

    </div>
    

    {% block content %}
    <div class="row">
      <div class="large-12 columns">
      	<div class="panel">
	        <h3 class="text-center">Pagina en Construccion. . . </h3>
        </div>
          <h1>sugerrencia para buscar: prueba, love, test, son, sweet</h1>
      </div>
    </div>


    {% endblock %}



     <footer style="background-color: #F8F8FA;">
        <div class="large-12 columns"><hr/>
          <div>
            <div class="large-12 columns">
              <form method="get" action="{% url 'bitlyric:search' %}">
                <div class="row collapse">
                  <div class="large-10 small-8 columns">
                    <input name="music" type="text" placeholder="Search lyrics . . . "/>
                  </div>

                  <div class="large-2 small-4 columns">
                      <input class="postfix button expand" type="submit" value="Search"/>
                  </div>
                </div>
              </form>
            </div>

                  <h4>Ultimas letras Publicadas. . .</h4>


                <ul class="large-3 columns">

                    {% for cancion in ult_canciones %}
                        <li>
                            <a href="{% url 'bitlyric:cancion' cancion.artistas.all.0.slug cancion.slug %}">{{ cancion.title }}</a>
                            |
                            <a href="{% url 'bitlyric:artista' cancion.artistas.all.0.slug %}">{{ cancion.artistas.all.0.name}}</a>
                        </li>
                    {% endfor %}

                </ul>


          </div>
        </div>
      </footer>


    
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
    {% block extra-js %}{% endblock %}

  </body>
</html>

templates/bitlyric/artist_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
      <div class="row">
        <div class="large-12 columns">



          <div class="row">



            <div class="large-4 small-12 columns">

{#              <img src="http://placehold.it/500x500&text=Artist">#}
                {% if artist.img %}
                    <img src="{{ artist.img.url }}" alt="{{ artist.name }}">
                {% else %}
                    <h3>{{ artist.name }}</h3>
                {% endif %}

              <div class="panel">
                <h3>{{ artist.name }}</h3>
              </div>

            </div>


            <div class="large-8 columns">

              <div class="row">

                {% for cancion in canciones %}

                  <div class="large-4 small-6 columns">

                      <a href="{% url 'bitlyric:cancion' artist.slug cancion.slug %}">

                          <img src="https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/music.png"
                               alt="music_logo"/>
                          <div class="panel">
                            <h5 class="text-center">{{ cancion.title }}</h5>
                          </div>
                      </a>

                  </div>

                {% endfor %}

              </div>

            </div>

          </div>


        </div>
      </div>

{% endblock %}

templates/bitlyric/index.html
{% extends 'base.html' %}
{% load staticfiles %}

templates/bitlyric/lyric_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
       {# seccion para la info del artista #}
       <aside class="large-3 columns">

          <img src="{{ artist.img.url }}">

          <div class="panel">
            <a href="{% url 'bitlyric:artista' artist.slug %}"><h3>{{ artist.name|title }}</h3></a>
            <h5 class="subheader">
                <ul>Search for {{ artist.name|title }}  lyrics: <input type="text"/>
                    {% for cancion in canciones %}
                        <a href="{% url "bitlyric:cancion" artist.slug cancion.slug %}">
                            <li>{{ cancion.title }}</li>
                        </a>
                    {% endfor %}

                </ul>
            </h5>
          </div>

        </aside>

        {# Seccion donde va la letra de la cancion #}
        <div class="large-5 columns" role="content">
          <article>

            <h3>{{ cancion.title|title }} Lyric</h3>

            <div class="row">
              <div class="large-12 columns">

                {{ cancion.letra }}

              </div>
            </div>

          </article>
        </div>

    {# Seccion donde va el video de la canion #}
    <div class="large-4 columns">
        <iframe src="http://www.youtube.com/embed/{{ cancion.link }}"
                width="100%"
                height="300"
                frameborder="0">
        </iframe>
    </div>


{% endblock %}

templates/bitlyric/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row">
    <h2>Busquedas relacionadas con <span style="color:#EEEEEE; background: #444444;border-radius:10px;"> "{{ searched }}" </span></h2>

        <ul>
            {% for cancion in canciones %}
                <a href="{% url 'bitlyric:cancion' cancion.artistas.all.0.slug cancion.slug %}"><li>{{ cancion.title }}</li></a>
            {% endfor %}
        </ul>

    </div>

{% endblock %}